#!/bin/bash

echo "Parsing $1..."
. $1
shift

UML_ARGS="umid=${USERNAME}"

UML_ARGS="$UML_ARGS mem=${MEMORY}m ncups=${NCPUS}"

for i in `seq 0 $(($NDISKS - 1))` ; do
    eval d=\$DISK$i
    UML_ARGS="$UML_ARGS ubd$i=$d"
done

UML_ARGS="$UML_ARGS initrd=./$INITRD"
UML_ARGS="$UML_ARGS hwprobe=-sys"

UML_ARGS="$UML_ARGS eth0=daemon,$MAC_ADDRESS"

if true ; then	# for installation

    UML_ARGS="$UML_ARGS ramdisk_size=65536"
    UML_ARGS="$UML_ARGS rootfstype=minix"

    UML_ARGS="$UML_ARGS con=pty ssl=none ssl0=xterm console=ttyS0"
    UML_ARGS="$UML_ARGS con3=xterm"

fi

UML_ARGS="$UML_ARGS $EXTRA_ARGS"

echo $KERNEL $UML_ARGS

# Create TAP device
/usr/bin/tunctl -t $TAP_DEVICE -u $USERNAME

# start uml_switch daemon
/usr/bin/uml_switch -tap $TAP_DEVICE -unix $TAP_DEVICE.ctl > /dev/null 2> /dev/null &

# enable UML user access to X session
/usr/X11R6/bin/xauth -f ./.Xauthority merge ~/.Xauthority
chown $USERNAME:users ./.Xauthority

# start UML machine
echo "Starting uml..."
/bin/su -s /bin/bash -c "./$KERNEL $UML_ARGS $*" $USERNAME
